// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import FlashController from "./flash_controller.js"
application.register("slash", FlashController)

import ValidateController from "./validate_Controller.js"
application.register("validate", ValidateController)

import TextLimiterController from "./text_limiter_controller.js"
application.register("text-limiter", TextLimiterController)
