default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url:  <%= ENV.fetch("DATABASE_URL") { 'localhost' } %>

development:
    <<: *default
    database: interview_development

test:
    <<: *default
    database: interview_test

production:
  <<: *default
  database: interview_production
  username: interview
  password: interview