default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: course_three
  username: postgres
  password: password
  host: localhost
  

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
