source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.4"
gem "rails", "~> 7.0.1"
gem "sqlite3", "~> 1.4"
gem "puma", "~> 5.0"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem 'bcrypt', '~> 3.1', '>= 3.1.12'
gem 'active_model_serializers', '~> 0.10.2'
# group :development, :test do
#   gem "debug", platforms: %i[ mri mingw x64_mingw ]
# end

group :development do
    gem 'faker', '~> 1.6', '>= 1.6.6'
    gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

