source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.4"
gem "rails", "~> 7.0.1"

# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 1.4"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem "rack-cors"

gem "active_model_serializers", "~> 0.10.12"

gem 'aws-sdk-s3'
# gem "google-cloud-storage", "~> 1.36", require: false
# gem 'dotenv', '~> 2.1', '>= 2.1.1'
# gem 'dotenv-rails', require: 'dotenv/rails-now'

# group :development, :test do
#   # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
#   gem "debug", platforms: %i[ mri mingw x64_mingw ]
# end

group :development do
    # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
    # gem "spring"
    # gem 'foreman', '~> 0.87'
    gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
    gem 'faker', '~> 1.6', '>= 1.6.6'
end
